version: '3.8'

services:
  # Zookeeper (Required by Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.1
    container_name: cc-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - shop-network

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.3.1
    container_name: cc-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"    # Cổng cho các dịch vụ bên trong Docker
      - "29092:29092"  # Cổng cho kết nối từ host
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - shop-network


  # Redis
  redis:
    image: redis:7.0
    container_name: cc-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - shop-network

  # MySQL for Order Service
  mysql-sales-checkout-service:
    image: mysql:8.0
    container_name: mysql-sales-checkout-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sales_checkout_db
    ports:
      - "3307:3306" # Host port 3307 mapped to container port 3306
    volumes:
      - mysql-sales-checkout-service-data:/var/lib/mysql
    networks:
      - shop-network

  # MySQL for Identity Service
  mysql-user-auth-service:
    image: mysql:8.0
    container_name: mysql-user-auth-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_auth_db
    ports:
      - "3308:3306" # Host port 3308 mapped to container port 3306
    volumes:
      - mysql-user-auth-service-data:/var/lib/mysql
    networks:
      - shop-network

  mysql-billing-transaction-service:
    image: mysql:8.0
    container_name: mysql-billing-transaction-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: billing_transaction_db
    ports:
      - "3309:3306" # Host port 3308 mapped to container port 3306
    volumes:
      - mysql-billing-transaction-service-data:/var/lib/mysql
    networks:
      - shop-network

  mysql-catalog-inventory-service:
    image: mysql:8.0
    container_name: mysql-catalog-inventory-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog_inventory_db
    ports:
      - "3310:3306" # Host port 3308 mapped to container port 3306
    volumes:
      - mysql-catalog-inventory-service-data:/var/lib/mysql
    networks:
      - shop-network

  mysql-inventory-service:
    image: mysql:8.0
    container_name: mysql-inventory-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory_db
    ports:
      - "3311:3306" # Host port 3308 mapped to container port 3306
    volumes:
      - mysql-inventory-service-data:/var/lib/mysql
    networks:
      - shop-network
  # Eureka Server
  eureka-server:
    image: commercecore/discovery-registry:latest
    container_name: discovery-registry
    depends_on:
      - kafka
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - shop-network

  # API Gateway
  api-gateway:
    image: commercecore/ingress-gateway:latest
    container_name: ingress-gateway
    depends_on:
      - kafka
      - eureka-server
    ports:
      - "9191:9191"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - shop-network

  # Order Service
  order-service:
    image: commercecore/sales-checkout-service:latest
    container_name: sales-checkout-service
    depends_on:
      - kafka
      - mysql-sales-checkout-service
      - eureka-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-sales-checkout-service:3306/sales_checkout_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - shop-network

  email-service:
    image: commercecore/notification-delivery-service:latest
    container_name: notification-delivery-service
    depends_on:
      - kafka
      - eureka-server
    ports:
      - "8086:8086"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - shop-network

  payment-service:
    image: commercecore/billing-transaction-service:latest
    container_name: billing-transaction-service
    depends_on:
      - kafka
      - mysql-billing-transaction-service
      - eureka-server
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-billing-transaction-service:3306/billing_transaction_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - shop-network

  product-service:
    image: commercecore/catalog-inventory-service:latest
    container_name: catalog-inventory-service
    depends_on:
      - kafka
      - mysql-catalog-inventory-service
      - eureka-server
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-catalog-inventory-service:3306/catalog_inventory_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_TIMEOUT: 60000
    networks:
      - shop-network

  stock-service:
    image: commercecore/inventory-service:latest
    container_name: inventory-service
    depends_on:
      - kafka
      - mysql-inventory-service
      - eureka-server
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-inventory-service:3306/inventory_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - shop-network
  # Identity Service
  identity-service:
    image: commercecore/user-auth-service:latest
    container_name: user-auth-service
    depends_on:
      - kafka
      - mysql-user-auth-service
      - eureka-server
    ports:
      - "9898:9898"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-user-auth-service:3306/user_auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - shop-network

volumes:
  mysql-sales-checkout-service-data:
  mysql-user-auth-service-data:
  mysql-catalog-inventory-service-data:
  mysql-billing-transaction-service-data:
  mysql-inventory-service-data:
  redis-data:
networks:
  shop-network:
    driver: bridge
